### ISSUE TITLE
Get icon by filetype

### ISSUE THREAD

**Issue by romgrk** [kyazdani42/nvim-web-devicons#29]
The icons are classified by filename and/or extension. It would be nice to be able to get an icon by filetype.

Eg vim's help files have the `help` filetype, but their extension is still `.txt`.

**Comment by kyazdani42** [comment]
i guess so, but a filetype is associated to a buffer, so you would need to load the buffer, assign it a file, then get the filetype. For a few files it would be ok, but for most use case it would be desatruously slow. Maybe providing a function geticonfromft would work

**Comment by romgrk** [comment]
Yes that is exactly what I mean. I want to pass the filetype not the file.

**Comment by kyazdani42** [comment]
well, you could add a PR i wouldn't be against it, but depending on your use case, wouldn't it be easier to just map filetypes to file extensions ? so you could only map those you would need (for instance, if your filetype is `help`, you can map to `.vim`, but otherwise it will load with the default extension)

**Comment by romgrk** [comment]
I think icons should be classified by filetype, not by extensions. And there should be a map from file extension to filetype. The reason is that filetype is more primordial than extension, because different extensions can point to the same filetype (C++: cpp, cxx, cc). Entries in the current icon table are repeated rigth now and that's wasted memory. I''m also mentionning because I've been having trouble with the `get_icon` function sometimes, I've seen a few stack overflows. I'm not sure where the icons memory lives, I would have expected on the heap, but anyway it's good to reduce memory usage. It will also be easier to maintain.

**Comment by kyazdani42** [comment]
i agree it would be better if it were classified by filetype.
Although i've never experienced stack overflows (and i believe lua, as a high level garbage collected language, stores everything in the heap ? I'm not sure about that tough). Is a 100 entry table really that big in memory ?
Is there a way to get the filetype from a filename in the neovim api ? I'm not aware of such function, although i've looked up documentation as well as i could :)
Also some filename would not match any filetypes i believe, so that could also potentially be another issue and we would still need to add an extension based table.

**Comment by romgrk** [comment]
The filetype doesn't necessarily depend on the name. Sometimes plugins will set the filetype on buffers just to get the syntax highlighting. Passing the filetype as an extra param or having a different function to get the icon by filetype would solve that issue. Separate function would be cleaner I think.

About memory, I would have expected lua to be fine but I have a lot of lua running currently (treesitter and a few plugins) and when I have lots of buffers open I often see a `Lua: can't grow stack past 4002...` error messages when calling `get_icon`. Can't say who is at fault but anyway less repetition is better.

**Comment by kyazdani42** [comment]
i believe your stack issue is related to vim <> lua code transfer. I can take a look to see if it happens on my machine with your barbar plugin, but i believe this is an issue for neovim.
Anyway make a Pr ill merge it :)

**Comment by BerkeleyTrue** [comment]
I'd like to second an api to find by filetype. It would simplify things greatly.

**Comment by kyazdani42** [comment]
closed in #125
