### ISSUE TITLE
Support plugins? (airline, nerdtree, ...)

### ISSUE THREAD

**Issue by entropitor** [kyazdani42/nvim-web-devicons#38]
Will this plugin ever support other plugins like airline, nerdtree, ...?

**Comment by akinsho** [comment]
I think this question is reversed. I'm not sure what support would look like/means in this case? If it means can these icons be used in those plugins then I think the onus to add this would be on airline or other plugins to somehow adds this functionality themselves and make this plugin a dependency not really the other way around.

For the most part other consumers of the plugin like `telescope.nvim`, `barbar.nvim`, `nvim-bufferline.lua`, `galaxyline.lua` have implemented integrations themselves without anything needing to be done on this plugin's side. Both plugins you mention are written in `vimscript` and would need to special case using this plugin to `nvim` with access to lua 🤷🏿‍♂️ which is possible but definitely something (IMO) for them to do if they wanted.

**Comment by entropitor** [comment]
Oh okay, I'm asking because when I also install https://github.com/ryanoasis/vim-devicons, airline and nerdtree get icon support out of the box, I assumed it was done by https://github.com/ryanoasis/vim-devicons and not by nerdtree, airline, ... but I could be mistaken

Given it was "a fork of" that project, I was expecting it to work out of the box as well. I get that it's not easy because of vim<>lua

**Comment by akinsho** [comment]
@entropitor I actually just dug through the devicons code base searching for `nerdtree` and `airline` and you're right vim-devicons specifically hooks into apis exposed by those plugins and integrates with them. Tbh only @kyazdani42 can give you a definitive answer but imo both those integrations each look to be quite a lot of vimscript, and really seem like they should have been done in the specific plugins not by vim-devicons since it seems to go beyond the remit of what is essentially an icon pack 🤷🏿‍♂️ .  Looks like it would be very awkward at best to try and make either of those plugins work with this package.

**Comment by entropitor** [comment]
Okay, that's a fair point. I was just wondering 👍

**Comment by kyazdani42** [comment]
Hi, yes i agree with akinsho, although it's a 'fork', i would like to preserve a library like functionality for this plugin. Implementing code for other plugins would be too much work and i do not aim for that. Also i've written my own tree plugin and that's when i had to rewrite vim-devicons because it was too slow and did not match my requirement in term of usability. People are free to fork and extend this to support plugins like nerdtree or airline though :)
