### ISSUE TITLE
Deferred highlighting with vim.schedule causes issue

### ISSUE THREAD

**Issue by romgrk** [kyazdani42/nvim-web-devicons#41]
The previous API was defininig the highlight groups synchronously. Now that `vim.schedule` is used, the function returns the HL group name but it's not defined yet because the scheduled function hasn't run yet.

Not sure why you've enabled that but I would tend to believe that this new behavior is incorrect.

Users of barbar.nvim who update their packages are all affected by this issue, LMK what's the ETA and resolution when you have more details.

Link: https://github.com/romgrk/barbar.nvim/issues/98

**Comment by kyazdani42** [comment]
fuuuu an user yesterday wanted to load hl groups when requested to load nvim faster. But then, telescope users reported that the get_highlight_name was causing errors because it's called asynchronously and suggested wrapping in vim.schedule.
I guess maybe we should just revert back to how it was before.

**Comment by kyazdani42** [comment]
should be fixed, sorry for the inconvenience

**Comment by romgrk** [comment]
Cool! Beyond the inconvenience, I do understand the point of making things snappier. If you're interested in reinstating the behavior, maybe we could work out an API that is async-aware? E.g. it could return `none` or a default HL group (Normal?) if the function is called before the devicon HL group is defined.

**Comment by kyazdani42** [comment]
telescope uses `get_highlight_name` in a lua callback, so when we moved the `nvim_command` call inside of it, it broke because vim functions need to be wrapped in a `schedule` call when used asynchronously.
This is not too important rn, async stuff should be treated with caution and maybe rethinking how to make it work would take more time. Breakage like this is not supposed to happen, maybe tests would be required at some point.
